### ISSUE TITLE
Add support for `Float64` for Clickhouse (SaaS)

### ISSUE THREAD

**Issue by ilongin** [iterative/datachain#12]
The problem is that if number that can only be represented with double precision, e.g `0.3813476562` is inserted using CH database (in SaaS), it's actually inserted as single precision (`Float32`) as python `float` is saved as `Float32` column type in database by default. This way precision of that value is **lost** for user. 

One solution is to support `datachain.sql.types` when defining output schema (currently only python basic values are supported together with `Feature` type).

Example that works for SQLite but fails for Clickhouse:
```python
import pandas as pd
from datachain.lib.dc import DataChain

num = 0.3813476562   # number that requires 64 bits to not loose precision
chain = DataChain.from_pandas(pd.DataFrame([[num]], columns=['number']))
assert chain.collect_one("number")[0] == num
```

**Comment by dmpetrov** [comment]
@ilongin is it still relevant or we can close?
Based on my understanding we are working with float64 only rn. Other types are not supported yet.

**Comment by ilongin** [comment]
@dmpetrov yes, looks like example in description works now so I'm closing this issue.

**Comment by skshetry** [comment]
I don't think we have made any changes to this. @ilongin, can you point me the commit that fixed this please?

**Comment by ilongin** [comment]
@skshetry I made a mistake testing this on SQLite DB instead of Clickhouse. Reopening it agan.

**Comment by dreadatour** [comment]
Let's discuss this approach, please? https://github.com/iterative/studio/pull/10528 🙏👀

**Comment by dreadatour** [comment]
Should be fixed now by related Studio issue.
