### ISSUE TITLE
`File.get_value()` is deprecated?

### ISSUE THREAD

**Issue by tibor-mach** [iterative/datachain#156]
I am using `File.get_value()` to process a JSON file with a UDF in datachain, but it seems that get_value is gone and the private `_get_value` method suggested by the error message below expects 8 positional arguments (so I doubt that is the right one to use)
```
AttributeError: 'File' object has no attribute 'get_value'. Did you mean: '_get_value'?
```
It is [this](https://github.com/iterative/datachain/blob/llm-tutorial/examples/llm/llm_chatbot_evaluation.ipynb) notebook again, and the relevant code is this:

```
class Metadata(DataModel):
    key: str
    title: str
    authors: list[dict[str, Optional[str]]]


# Use signatures to define input/output types (these can be Feature or regular Python types)
def extract_metadata(file: File) -> Metadata:
    import json
    # Ingest the file
    metadata = json.loads(file.get_value())

    record = dict()
    record["key"] = file.name.removesuffix("Metadata.json")+"Paper.pdf"
    record["title"] = metadata["title"]
    record["authors"] = metadata["authors"]

    return Metadata(**record)
```

Maybe @dberenbaum would know? I don't think this is a bug, only a change in the API.

**Comment by dberenbaum** [comment]
Yes, it's been replaced by `.read()`. Sorry about that!

**Comment by rlamy** [comment]
It's been renamed to `File.read()`, see #102
