### ISSUE TITLE
Missing datasets.ipynb

### ISSUE THREAD

**Issue by rlamy** [iterative/datachain#179]
From https://discord.com/channels/485586884165107732/565759186693128202/1265662730313007206
> at datachain docs ,  at the end of "Reading external metadata" paragraph is link to "datasets.ipynb" at examples, but no such notebook at repo. check it, please.

**Comment by mattseddon** [comment]
@volkfox looks like you added this in https://github.com/iterative/datachain/pull/128 [here](https://github.com/iterative/datachain/pull/128/files#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6R284). Any ideas?
