### ISSUE TITLE
CLI "datachain ls" command broken

### ISSUE THREAD

**Issue by volkfox** [iterative/datachain#202]
### Description

$ datachain ls  'gs://datachain-demo/dogs-and-cats/'
Error: 'content-type'

### Version Info

```Text
datachain -V
0.2.6.dev4+gef2347f

python -V
Python 3.9.4
```

**Comment by dmpetrov** [comment]
I put it in backlog since it's not a part of the public API anymore and File/path might be a prerequisite.

**Comment by volkfox** [comment]
cant repro in a clean environment
