### ISSUE TITLE
`limit()` ignored after `show()`

### ISSUE THREAD

**Issue by rlamy** [iterative/datachain#219]
In some cases, `.limit()` seems to have no effect. Here's a reproducer:
```python
from datachain import DataChain

img_dc = DataChain.from_storage("gs://datachain-demo/newyorker_caption_contest/images")
img_dc.show(3)
assert img_dc.limit(10).count() == 10
```
Commenting out `img_dc.show(3)` makes the assert succeed as expected.

Note that I've only been able to reproduce the failure with a real bucket, but not in tests.

**Comment by rlamy** [comment]
The issue actually arises when setting a higher limit on the same chain, as in:
```python
dc.limit(5)
dc.limit(10)
```
This is caused by #206 modifying `dc` instead of only the result of `dc.limit()`.

**Comment by mattseddon** [comment]
My bad, sorry. Hopefully, #225 has fixed the mess I created.
