### ISSUE TITLE
Introduce window-function

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#227]
I have a dataset with column `Class` which takes one of categorical values like Dog, Cat etc...  

- [ ] I need to select a subset of the records with 5 records in each class.
- [ ] I need the same but the subset has to be randomized.

This is how it looks like in IBIS (with randomization):
```python
# Create a random column for ordering
random_col = table.mutate(random_val=ibis.random())

# Define a window function partitioned by 'Class' and ordered by the random column
window = win.Window(partition_by='Class', order_by=random_col.random_val)

# Add a row number column based on the window function
ranked_table = random_col.mutate(row_number=ibis.row_number().over(window))
```

**Comment by dreadatour** [comment]
Merged. Will continue in the follow-up issues https://github.com/iterative/datachain/issues/522 and https://github.com/iterative/datachain/issues/523
