### ISSUE TITLE
from_parquet() return type

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#231]
It seems there’s an issue with the return types.

PyCharm identifies `from_parquet()` returns a wrong type (see next mutate() command in the screenshot).
If I change from_parquet() return value to "Self" - the issue disappears.

I'm not sure I fully understand the issue but we need to figure out some systematic fix for this.

<img width="501" alt="Screenshot 2024-08-03 at 12 16 38 PM" src="https://github.com/user-attachments/assets/0adcd23e-fbcc-484b-9144-2e36b3eef34c">

Notably, from_storage() and gen() do not have this issue:
<img width="454" alt="Screenshot 2024-08-03 at 12 34 58 PM" src="https://github.com/user-attachments/assets/b8bcdbae-f051-4250-9551-a1ed49bd5518">

**Comment by EdwardLi-coder** [comment]
Hi @dmpetrov .I think using generics and type variables is a good solution.like this
`from typing import TypeVar, Type

T = TypeVar('T', bound='DataChain')

class DataChain:
    @classmethod
    def from_parquet(
        cls: Type[T],
        path,
        partitioning: Any = "hive",
        output: Optional[dict[str, DataType]] = None,
        object_name: str = "",
        model_name: str = "",
        source: bool = True,
        nrows=None,
        **kwargs,
    ) -> T:
        ...`

**Comment by dmpetrov** [comment]
> ```python
> T = TypeVar('T', bound='DataChain')
> ```

Yep! It looks like a right direction. Thank you @EdwardLi-coder!

Please feel free to propose a PR 🙂  Otherwise, I someone from the team can pick it up.

**Comment by skshetry** [comment]
`from_parquet` type hint is correct, and does not look like is a problem. It's likely to do with `mutate` lacking any type hints (with `@detach` decorator).


Anyway, this looks like a bug on Pycharm to me. Mypy and pyright don't show any errors/warnings.

I get a different error on Pycharm than you have though:

```
Parameter(s) unfilled Possible callees: (..., ...: ParamSpec("P")) 
```

Which makes me think it's a bug in Pycharm.

**Comment by EdwardLi-coder** [comment]
> > ```python
> > T = TypeVar('T', bound='DataChain')
> > ```
> 
> Yep! It looks like a right direction. Thank you @EdwardLi-coder!
> 
> Please feel free to propose a PR 🙂 Otherwise, I someone from the team can pick it up.

OK,I will submit PR.

**Comment by shcheklein** [comment]
I thinks this can be closed now. Thanks @EdwardLi-coder !
