### ISSUE TITLE
Generator function to list bucket

### ISSUE THREAD

**Issue by ilongin** [iterative/datachain#244]
We should create new generator function that will go to some bucket URI and do the listing.

Idea is to have something like

```python
ds = (
    DataChain.from_empty(schema=...)
   .gen(file=list_bucket("s3://ldb-public", spec=File))
   .save("ldb_public_lst")
)
```

Blocked by https://github.com/iterative/datachain/pull/248

**Comment by mnrozhkov** [comment]
@ilongin, what is the scenario when this feature is important? Why `from_storage` is not enough?
