### ISSUE TITLE
`@skip_if_not_sqlite` incompatibility with pytest-dotenv

### ISSUE THREAD

**Issue by rlamy** [iterative/datachain#262]
When running Studio tests locally using an envfile, e.g. with `pytest --envfile=.env.test ../../../datachain/tests`, `@skip_if_not_sqlite` is ignored. It's probably happening because `tests.utils` is imported early, before pytest-dotenv modifies the enviroment.

**Comment by mattseddon** [comment]
FWIW, the command used in the CI works. 

E.g. `pytest --config-file=pyproject.toml ../../../datachain/tests -k test_pull_dataset_not_found_in_remote -v` returns:

```
Results (2.46s):
       1 skipped
    2249 deselected
```

**Comment by rlamy** [comment]
Right, looking at the code of pytest-dotenv, that seems to be a limitation of the plugin: `--config-file` loads the env earlier than `--envfile`. I guess we only need to document it in Studio.
