### ISSUE TITLE
Readme uses outdated mistral lib

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#268]
Mistral lib was updated to 1.0 a week ago with changes in API. The current readme might not even work with the new mistal.

**Comment by shcheklein** [comment]
I think we should copy this code over to example (or do we have it there already?) and run as a test on CI so that we can quickly detect the issues. @mattseddon wdyt?

**Comment by mattseddon** [comment]
We could strip the code from the markdown using regex to avoid duplication but the example needs a `MISTRAL_API_KEY`.  I'd assume we would get billed every time the example runs in the CI (much like the examples using an `OPENAI_API_KEY` or `ANTHROPIC_API_KEY`). If this isn't the case or we're willing to accept the cost I'll need to be provided with the key.

**Comment by dmpetrov** [comment]
Resolved by #270
