### ISSUE TITLE
Document the column renaming capability of mutate() 

### ISSUE THREAD

**Issue by volkfox** [iterative/datachain#298]
### Description

Currently mutate() can rename a column.
This is a useful feature which is not documented and not intuitive because normally mutate() cannot modify existing columns.

We need to document/support this behavior.

```
>>> ds1.show()
Processed: 1 rows [00:00, 1191.90 rows/s]
Generated: 5 rows [00:00, 6925.87 rows/s]
   key  newky
0    0      1
1    2      3
2    2      3
3    2      3
4    5      6
>>> ds1.mutate(oldkey=Column("newky")).show()
Processed: 1 rows [00:00, 832.53 rows/s]
Generated: 5 rows [00:00, 4363.61 rows/s]
   key  oldkey
0    0       1
1    2       3
2    2       3
3    2       3
4    5       6
```

**Comment by srini047** [comment]
Hi,
I would like to take up this issue. Just a confirmation if it needs to be updated [here](https://datachain.dvc.ai/references/datachain/#datachain.lib.dc.DataChain.mutate).

**Comment by dmpetrov** [comment]
Yes, mutate() creates a new column. It's the primary goal of the function.

Renaming is just a corner case when a new column matches the input column.

**Comment by srini047** [comment]
Thanks for the prompt response. But in the above scenario, I mutate the column `file.source` which exists. But still it creates a new one. So I am a bit confused.

> Yes, mutate() creates a new column. It's the primary goal of the function.
> 
> Renaming is just a corner case when a new column matches the input column.

**Comment by dmpetrov** [comment]
Got it. In the example, you create a column 'source' from a column 'file.source' which is a different column 🙂

**Comment by dmpetrov** [comment]
.print_schema() can give you a slightly better perspective to the column names I hope

**Comment by shcheklein** [comment]
Are there cases where the existence of the previous column (the regular mutate behavior AFAIU) would be required 🤔 ? It's an interesting edge case but does it deserve to making a corner / special case in `mutate` behavior? (rename hopefully can be achieved with select commands?).
