### ISSUE TITLE
Method `.to_pandas(flatten=True)` returns DataFrame of NaN values

### ISSUE THREAD

**Issue by mnrozhkov** [iterative/datachain#328]
### Description

Code to reproduce: 
```python
DataChain.from_storage('gs://datachain-demo/dogs-and-cats/cat.1009.jpg', type='image').to_pandas(flatten=True)
```

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/065ff961-f438-4728-8216-7b3e8a0a758a">

### Version Info

```Text
0.3.4
Python 3.12.4
```

**Comment by shcheklein** [comment]
Looking into this, since I was the last one to touch this code. Can be a regression of some sort.
