### ISSUE TITLE
DataChain Telemetry needed

### ISSUE THREAD

**Issue by jendefig** [iterative/datachain#344]
### Description

We need to add DataChain telemetry to the roadmap to begin tracking usage since it is open now! 😄 🚀 🎉

**Comment by shcheklein** [comment]
We have a common library that we should utilize https://github.com/iterative/telemetry-python .

**Comment by skshetry** [comment]
Is https://pypistats.org/packages/datachain not enough?

**Comment by shcheklein** [comment]
> Is https://pypistats.org/packages/datachain not enough?

hmm ... it's super noisy and doesn't show MAU / DAU at all. Really hard to understand actual engagement, not enough visibility into what features are the most important ones
