### ISSUE TITLE
Remove `Catalog.merge_datasets()`

### ISSUE THREAD

**Issue by ilongin** [iterative/datachain#349]
Current implementation doesn't really work with our new feature schemas from `lib` and is also not really used from anywhere except from CLI. 

We already have`DataChain.merge()` which maybe can be used instead, but we need to check if dataset dependencies are handled in a right way with that one. 
Maybe we can also remove CLI command for this as well as it seems kind of random to have that there(this is more of a product decision though)

**Comment by dmpetrov** [comment]
Let's remove it!
It's not even clear how to use merge_dataset() without merge condition. It seems like very specific use case.
