### ISSUE TITLE
Consolidation of datachain examples with unstructured

### ISSUE THREAD

**Issue by tibor-mach** [iterative/datachain#353]
That one is a bit different as it summarises the text. But otherwise it is rather similar in what it does, so I guess we could simply add one more column to the example with embeddings where we have the text summary for the entire article.

We have [this](https://github.com/iterative/datachain/blob/main/examples/llm_and_nlp/unstructured-text.py) example with `unstructured` which shows text summarisation and then [this](https://github.com/iterative/datachain-examples/blob/main/llm/pdf-processing/pdf-processing.py) example which chunkifies text and creates embeddings. Otherwise they are very similar.

I would merge the two, deleting the example from the datachain [repo](https://github.com/iterative/datachain) and adding article text summary to the output in [this example](https://github.com/iterative/datachain-examples/blob/main/llm/pdf-processing/pdf-processing.py) in datachain-examples.

 @mattseddon @dberenbaum (you seem to have worked on the summarisation example) do yo agree?

cc @shcheklein

**Comment by shcheklein** [comment]
> I would merge the two, deleting the example from the datachain [repo](https://github.com/iterative/datachain)

I think it's better to keep in the datachain repo if possible. It's not a jupyter notebook, we already have tests for this. Atm datachain-examples doesn't look stable tbh, doesn't have a good structure, linters, etc, etc, etc.

This example has become one of the basics one we show to users.

**Comment by shcheklein** [comment]
> I don't see a clear rule by which to keep examples in one repo or the other at the moment.

I think we wanted to migrate notebooks initially? that was pretty much the rule

if it's a single script that can run (on a subset of data) sufficiently fast and represents a high-level use case / example - I think we can keep it in the main repo

> Well, in that case I would just keep both of them as they are.

could you clarify this a bit? what would be the reason to have / maintain two of them?

**Comment by shcheklein** [comment]
sounds good @tibor-mach !
