### ISSUE TITLE
Remove support for executing last expression in the script

### ISSUE THREAD

**Issue by skshetry** [iterative/datachain#360]

**Comment by skshetry** [comment]
A couple of questions:

1) Do we need to show previews for multiple datasets, given that there can be multiple `save()`s within the script? Or, is it okay to show the last one that wins? 

2) Since we don't have any custom wrapper, we won't be able to show previews for temp datasets or `persist()`-ed dataset in `datachain query` command. I guess that would be okay? Same in Studio.

Since we won't be wrapping the datasets, the only way for us to know what datasets were created in the script is by using `job_id`.

**Comment by skshetry** [comment]
Looks like we will still need some kind of wrapper for "metrics" to work.

**Comment by shcheklein** [comment]
> Do we need to show previews for multiple datasets, given that there can be multiple save()s within the script? Or, is it okay to show the last one that wins?

Yes, I think that's fine to show the last one.

> Since we don't have any custom wrapper, we won't be able to show previews for temp datasets or persist()-ed dataset in datachain query command. I guess that would be okay? Same in Studio.

could you point to the code that wraps it / add a bit more details?
