### ISSUE TITLE
from_storage using File objects

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#38]
We need to optimize from_storage() and extract the listing operations to application level.

### Optimization problem

Now, from_storage() runs in two stages
1. creates a table with "old" schema signals like "source", "parent", "name" ...
2. converts these signals to `File` objects.

It needs to be done in one-pass.

### Listing in core codebase problem

We clearly can utilize our `gen()` machinery for this and simplify the core codebase.

### Requirements

1. We need a function for `gen()` that lists a specified bucket.
     - it's ok to use multithreading if needed
2. Keep `from_storage()` as is but it should use the generator function from the above(1).
     - the only new params is required - `name: str = "file` to specify the object name
4. We might need a special functionality in the API to generate a special table, not dataset (`ds_name_1`)
5. (Optional) "partial indexing" can be done separately if it cases many issues. We can start listing whole buckets at the begging.

**Comment by shcheklein** [comment]
@ilongin please consolidate with your tickets and epic if it makes sense

**Comment by ilongin** [comment]
Closing in the favor of more recent duplicate issue https://github.com/iterative/datachain/issues/266
