### ISSUE TITLE
Add `from_sql` / `from_database` factory method

### ISSUE THREAD

**Issue by shcheklein** [iterative/datachain#463]
Some users that I'm having conversations with have their labels, metadata already stored in PG.

E.g. they do this because the same database has UI / workflow for people who label data, or even is being used as a production database (backend). So, we most likely won't be able to replace those databases, at least not quickly.

We should add something like:

`DataChain.from_database(connection_string=..., sql="...")`

**Comment by shcheklein** [comment]
@skshetry yes, you are right!

**Comment by shcheklein** [comment]
Question / suggestion from @dmpetrov . Can we do this as a UDF function for now, what would be the difference?

**Comment by skshetry** [comment]
We already have `from_values()` that can be used by users. I think it supports iterators. 

So I don't even see benefit from this, except of being a syntax sugar (which we have too many already).

Also feels like we are making up for lack of docs/guides.

**Comment by shcheklein** [comment]
Yep, makes sense. Let me close this, try from_values / udf and get back to this is if I see we need this in some real examples.
