### ISSUE TITLE
Kaggle: UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x78574cfee2a0>

### ISSUE THREAD

**Issue by Aisuko** [iterative/datachain#465]
### Description

Thanks for your great work.

This issue isn't always happening.

```
!pip install -U -q pillow
!pip install -q ipywidgets datachain[torch] git+https://github.com/openai/CLIP.git
```

Code
```
from datachain import C, DataChain
from datachain.sql.functions import path

img_dc = DataChain.from_storage("gs://datachain-demo/newyorker_caption_contest/images", type="image", anon=True)

meta_dc = DataChain.from_parquet("gs://datachain-demo/newyorker_caption_contest/new_yorker_meta.parquet")
dc = img_dc.merge(meta_dc, on=path.name(img_dc.c("file.path")), right_on="filename")
sample = dc.filter(C("file.path").endswith("/371.jpeg")).limit(1)
sample_results = list(sample.collect("file", "caption_choices", "label"))
first_pair=sample_results[0]
image=first_pair[0].read()
```

Error log
```
---------------------------------------------------------------------------
UnidentifiedImageError                    Traceback (most recent call last)
Cell In[10], line 2
      1 first_pair=sample_results[0]
----> 2 image=first_pair[0].read()

File /opt/conda/lib/python3.10/site-packages/datachain/lib/file.py:435, in ImageFile.read(self)
    433 """Returns `PIL.Image.Image` object."""
    434 fobj = super().read()
--> 435 return Image.open(BytesIO(fobj))

File /opt/conda/lib/python3.10/site-packages/PIL/Image.py:3298, in open(fp, mode, formats)
   3296 if hasattr(obj, "tobytes"):
   3297     obj = obj.tobytes()
-> 3298 elif hasattr(obj, "tostring"):
   3299     obj = obj.tostring()
   3300 else:

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x78574cfee2a0>
```

The entire notebook see https://www.kaggle.com/code/aisuko/fine-tuning-clip-on-cartoon-images/notebook

### Version Info

```Text
0.3.18
Python 3.10.14
```
```

**Comment by shcheklein** [comment]
@Aisuko thanks! could you try to run a simpler version:

```
from datachain import DataChain, C

img_dc = DataChain.from_storage("gs://datachain-demo/newyorker_caption_contest/images", type="image", anon=True)

sample = img_dc.filter(C("file.path").endswith("/371.jpeg")).limit(1)
sample_results = list(sample.collect("file"))

first_pair=sample_results[0]
image=first_pair.read()
```

locally and on Kaggle?

(it might be related to some packages incompatibility)

**Comment by shcheklein** [comment]
Does it happen only when you run it remotely on Kaggle?

**Comment by Aisuko** [comment]
> Does it happen only when you run it remotely on Kaggle?

Yes

**Comment by Aisuko** [comment]
> @Aisuko thanks! could you try to run a simpler version:
> 
> ```python
> from datachain import DataChain, C
> 
> img_dc = DataChain.from_storage("gs://datachain-demo/newyorker_caption_contest/images", type="image", anon=True)
> 
> sample = img_dc.filter(C("file.path").endswith("/371.jpeg")).limit(1)
> sample_results = list(sample.collect("file"))
> 
> first_pair=sample_results[0]
> image=first_pair.read()
> ```
> 
> locally and on Kaggle?
> 
> (it might be related to some packages incompatibility)

I still got the same error.

**Comment by shcheklein** [comment]
It seems that kernel restart is needed after `pip install ...`. Otherwise it's not picking up the latest pillow. 

Could you try that?

It works for me on a simple example. Not sure how we can automatically do this. Colab and Kaggle come with a lot of packages installed, some of them are loaded by default, I'm not sure we can control it.

**Comment by Aisuko** [comment]
> It seems that kernel restart is needed after `pip install ...`. Otherwise it's not picking up the latest pillow.
> 
> Could you try that?
> 
> It works for me on a simple example. Not sure how we can automatically do this. Colab and Kaggle come with a lot of packages installed, some of them are loaded by default, I'm not sure we can control it.

HI @shcheklein thanks. It(kernel restart) works for me on a live session.

**Comment by shcheklein** [comment]
Okay, I think we can close this for now. I think it's not unique to DataChain and comes down to the Kaggle default image.
