### ISSUE TITLE
Feature request: Automatically cast merge keys

### ISSUE THREAD

**Issue by tibor-mach** [iterative/datachain#509]
### Description

Currently, the `.merge` method of `DataChain` expects both keys to be of the same type. This makes sense, but it would improve developer's quality of life a lot of e.g. it managed to automatically recast `int` to `str` or vice versa when one key is `int` and the other is `str`

**Comment by shcheklein** [comment]
@tibor-mach do you know if the regular databases do this? how the result column type is defined?

**Comment by shcheklein** [comment]
Let's close this for now then. I think it's better probably to have some features upstream to have the right types in the first place tbh.
