### ISSUE TITLE
Mac OS tests are slow are constantly failing in CI/CD

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#51]
### Description

I've noticed this in the past week or so.

- [ ] MacOS tests run for 12 minutes while the other OS tests about 5-6 minutes.
      - `macos-latest, 3.12` fails more often based on my observations
- [ ] Very often MacOS tests fail (running time limitation?) and I have to rerun them again.

<img width="855" alt="Screenshot 2024-06-24 at 12 43 04 PM" src="https://github.com/iterative/dvcx/assets/10081867/bcd9680f-1918-4e9c-9f99-5573cd8d5de1">
<img width="755" alt="Screenshot 2024-06-24 at 12 35 30 PM" src="https://github.com/iterative/dvcx/assets/10081867/146d3832-70f5-4454-80f7-2fa6ffa6fcf7">

**Comment by skshetry** [comment]
@0x2b3bfa0, any updates on this?

**Comment by 0x2b3bfa0** [comment]
@skshetry, yes: all (most of?) the failures were due to `azurite` flakiness as I stated on https://github.com/iterative/datachain/issues/51#issuecomment-2228958999; thanks a lot for fixing it on #174!
