### ISSUE TITLE
Bug: hierarchical columns and the `.select` method

### ISSUE THREAD

**Issue by tibor-mach** [iterative/datachain#510]
### Description

If the name of a top level colum which contains some subcolumns is the same as a level of a 1-level colum, the `.select` method seems to only select the multilevel column.

Example:
If I have `meta.id` and `meta.doc` and then also another column called `meta` , then `.select("meta")` only seems to select the former two.

### Version Info

0.5.1
Python 3.12.6

**Comment by shcheklein** [comment]
I'm not sure it should be allowed at all - to have a nested column `meta` and a regular field `meta` at the same time. Would it be a deal breaker for the scenario if we put a limitation like that @tibor-mach ?

**Comment by shcheklein** [comment]
Closing this in favor of for now https://github.com/iterative/datachain/issues/519
