### ISSUE TITLE
Feature request: `DataChain.unique`

### ISSUE THREAD

**Issue by tibor-mach** [iterative/datachain#511]
### Description

 To avoid having to use pandas in a situations like  [this](https://gitlab.com/iterative.ai/cse/customers/7-eleven/qco-image-catalog-dvcx/-/blob/main/scripts/qco-3-train-model.py?ref_type=heads#L27-29) (during model training) we need to be able to implement the [unique](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.unique.html) method (potentially also [nunique](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html))

**Comment by shcheklein** [comment]
@tibor-mach could you please update link `this` in the description? 

(and probably put a simple sample code here as well to get some sense and so that it is not expired and visible publicly)

**Comment by mattseddon** [comment]
Isn't this the same as `distinct`?

From the unique docs:

```python
>>> pd.unique(pd.Series([2, 1, 3, 3]))
array([2, 1, 3])
```

This passes:

```python
def test_distinct(test_session):
    dc = DataChain.from_values(
        val=[2, 1, 3, 3], other_val=["a", "b", "c", "d"], session=test_session
    )

    assert sorted(dc.collect("val")) == [1, 2, 3, 3]
    assert sorted(dc.distinct("val").collect("val")) == [1, 2, 3]
```
