### ISSUE TITLE
Reorganize the cli commands with groups

### ISSUE THREAD

**Issue by amritghimire** [iterative/datachain#576]
Can be a follow up, but let's rename all these command (similar to `ls-dataset` that we had). Can we make it all part of the `datachain datasets` umbrella for example - at least for now. (make `datasets` alias with `ds` to make it simpler)

datachain ds ls
datachain ds rm
datachain ds rename (better to have an explicit command vs one edit that is not very clear in terms of its semantics).

_Originally posted by @shcheklein in https://github.com/iterative/datachain/issues/572#issuecomment-2463030028_

**Comment by ilongin** [comment]
We are talking about this issue literally from the beginning of datachain but it always ended up at the end of the queue somehow :) .. it would be nice if we could finally do it.
Related old issue https://github.com/iterative/dvcx/issues/372

**Comment by amritghimire** [comment]
related to the groups of commands, etc - let's please make API also clean

`datachain/datasets/ls` 
`datachain/datasets/rename` 

-etc 

`rm-dataset` and similar look very weird for REST api.

_Originally posted by @shcheklein in https://github.com/iterative/datachain/pull/572#discussion_r1834853298_
