### ISSUE TITLE
Improve split Dataset into train / test / eval

### ISSUE THREAD

**Issue by dreadatour** [iterative/datachain#606]
See original issue: https://github.com/iterative/datachain/issues/603

Some improvements we may want to be implemented:

**Seed**. Seed is usually implemented by XOR-ing: sys.rand ^ seed if seed is provided or without any XOR if not provided.
if XOR is not implemented yet and it takes time to implement we can implement it without seed for now.

**Shuffle**. Optional, as using sys.rand makes it shuffled by default. If we need shuffle=False at some point we might consider using sorting and sys.id instead. But I'm not sure shuffle=False is very practical in real applications.

**Comment by dmpetrov** [comment]
> **Shuffle**.

It's not needed. See https://github.com/iterative/datachain/issues/603#issuecomment-2479864068

**Comment by 0x2b3bfa0** [comment]
Closed with https://github.com/iterative/datachain/pull/678
