### ISSUE TITLE
YOLO: Combined model is needed

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#624]
### Description

To vissualize all possible signals we need something like this:

```python
class MyYolo(DataModel):   # <--- this or something similar should be built-in, ideally with a single function like `from_result()`
    bbox: model.ultralytics.YoloBBoxes
    segm: model.ultralytics.YoloSegments
    poses: model.ultralytics.YoloPoses


def process(yolo: YOLO, yolo_segm: YOLO, yolo_pose: YOLO, file: File) -> MyYolo:
    img = Image.open(BytesIO(file.read()))
    return MyYolo(
        bbox=model.ultralytics.YoloBBoxes.from_results(yolo(img, verbose=False)),
        segm=model.ultralytics.YoloSegments.from_results(yolo_segm(img, verbose=False)),
        poses=model.ultralytics.YoloPoses.from_results(yolo_pose(img, verbose=False))
    )


(
    DataChain
    .from_storage("gs://mpii-human-pose")
    .limit(100)
    .setup(
        yolo=lambda: YOLO("yolo11n.pt"),
        yolo_segm=lambda: YOLO("yolo11n-seg.pt"),
        yolo_pose=lambda: YOLO("yolo11n-pose.pt")
    )
    .map(my_yolo=process)
    .save("mpii-human-pose-segment")
)
```

An idea: from_result() can have options like `from_result(bbox=True, segm=True, poses=True)`

**Comment by shcheklein** [comment]
> To vissualize all possible signals we need something like this:


@dmpetrov is it opposed to something that we have now? can you give a bit more details please?

**Comment by dmpetrov** [comment]
@shcheklein could you please clarify the question?

**Comment by shcheklein** [comment]
@dmpetrov I guess my question is - that code that you shared, is it something that we do now? E.g. do I have to do a custom `MyYolo` to visualize multiple signals now?

**Comment by dreadatour** [comment]
> E.g. do I have to do a custom MyYolo to visualize multiple signals now?

To visualize multiple kind of signals (e.g. both poses and segments the same time) — yes, either custom model or two signals with build-in models.
This will also requires setup multiple models (like one for poses and another one for segments).

**Comment by shcheklein** [comment]
> yes, either custom model or two signals with build-in models.

yep, thanks! Q: what is the value then to do a combined model, can we just always return multiple independent (built in?) models?

**Comment by dreadatour** [comment]
Since we now have `toolkit` module, I can add helpers there for YOLO visualization 👀

**Comment by dreadatour** [comment]
_Intermediate progress_

Was thinking to merge all Yolo signals into one model, but it is not possible in general. Each Yolo model returns different set of signals (obviously), for example, taking the following image:

![Image](https://github.com/user-attachments/assets/4eb841b9-2bb6-41bf-87a2-55b3c2064f4c)

Running three different models we get different set of signals:

### Model **yolo11n.pt** (bounding boxes)

Signals: `["person", "bottle", "dining table", "vase", "microwave", "vase", "potted plant"]`

![Image](https://github.com/user-attachments/assets/d48035f9-7a91-452a-91cf-2869daba8b1f)

### Model **yolo11n-pose.pt** (poses)

Signal: `["person"]`

![Image](https://github.com/user-attachments/assets/4262dde4-22d1-4418-8167-9d4cbdd4444c)

### Model **yolo11n-seg.pt** (segments)

Signals: `["person", "dining table", "bottle", "vase", "potted plant", "bottle"]`

![Image](https://github.com/user-attachments/assets/455eee13-393d-475d-b219-8fe6618f4ef4)

---

Only way I can see to have all these signals in one model is model, suggested by @dmpetrov:

```
class MyYolo(DataModel):   # <--- this or something similar should be built-in, ideally with a single function like `from_result()`
    bbox: model.ultralytics.YoloBBoxes
    segm: model.ultralytics.YoloSegments
    poses: model.ultralytics.YoloPoses
```

I am not really sure yet if it will be useful to have this model in DataChain source code and how it should looks like 🤔

**Comment by dmpetrov** [comment]
Let's close until we have clear way of doing this
