### ISSUE TITLE
`datachain.lib.dc.DatasetPrepareError` when saving, loading, and saving parquet datasets using `to_parquet` and `from_parquet`

### ISSUE THREAD

**Issue by AlamHasabie** [iterative/datachain#725]
## Background
I'm following this tutorial [here](https://github.com/shcheklein/example-datachain-dvc) to produce the `.parquet` representation of a dataset. While I'm able to generate the `.parquet` file and deserialize it, there's a problem when trying to save and load repeatedly in certain orders.

## Setup
1. Create a folder containing some random files
2. Use `from_storage` method and export the dataset using `to_json`. Call this script `save_parquet.py`
```python
from datachain import DataChain
dataset_chain = DataChain.from_storage(
    LOCAL_DATASET_URI,
    update=True
)

dataset_chain.to_parquet(PARQUET_PATH)
```

3. Now create a script to load the parquet. Let's call this `load_parquet.py`
```python
dataset = DataChain.from_parquet(PARQUET_PATH)
```

4. In order, call `save_parquet.py`, `load_parquet.py`, `save_parquet.py` and then `load_parquet.py`

## Expected Behavior
The second call to `load_parquet.py` converts the `.parquet` files correctly.

## Additional Notes
1. This error seems to happen only if the `.parquet` file is mixed up with other files, for example mixed with above sample scripts. I haven't been able to replicate the issue if I were to isolate the `.parquet` file under single directory as in the tutorial e.g.  under `data/dataset.parquet`. I decided to keep reporting this in case the behavior described in this issue is still unexpected.

## Error
```
Traceback (most recent call last):
  File "~/miniconda3/envs/datachain/lib/python3.10/site-packages/datachain/lib/dc.py", line 1877, in parse_tabular
    schema = infer_schema(self, **kwargs)
  File "~/miniconda3/envs/datachain/lib/python3.10/site-packages/datachain/lib/arrow.py", line 116, in infer_schema
    return pa.unify_schemas(schemas)
  File "pyarrow/types.pxi", line 3648, in pyarrow.lib.unify_schemas
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Must provide at least one schema to unify.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/Documents/datachain/test_load_parquet.py", line 5, in <module>
    dataset = DataChain.from_parquet(parquet_path)
  File "~/miniconda3/envs/datachain/lib/python3.10/site-packages/datachain/lib/dc.py", line 2045, in from_parquet
    return chain.parse_tabular(
  File "~/miniconda3/envs/datachain/lib/python3.10/site-packages/datachain/lib/dc.py", line 1880, in parse_tabular
    raise DatasetPrepareError(self.name, e) from e
datachain.lib.dc.DatasetPrepareError: Dataset processing prepare error: Must provide at least one schema to unify.
```

## Environment and Versions
python==3.10.15
datachain==0.7.11
OS : Ubuntu 24.04 LTS   

### Version Info

```Text
0.7.11
Python 3.10.15
```

**Comment by shcheklein** [comment]
Hmm, can't reproduce it right away. Can you give an example of the `PARQUET_PATH` path that triggers this behavior?

Also what kinds of files are around that parquet? Can you share please?

**Comment by AlamHasabie** [comment]
Hi @shcheklein 

1. The triggering PARQUET_PATH is something like this : 
```python
PARQUET_PATH = os.path.join("file://", os.getcwd(), "dataset.parquet")
```
2. I've created a public repo here : https://github.com/AlamHasabie/datachain-issue-725, in case you want more reproducibility.

**Comment by shcheklein** [comment]
Thanks @AlamHasabie a lot for the excellent reproducible script. I managed to find the issues:

- [ ] Error message should be improved. `from_parquet` fails with this error if there are no files found. We should be printing - file not found / files not found.
- [ ] There was a an error in how we pick the listing I think https://github.com/iterative/datachain/pull/726 cc @ilongin . (I'll update that PR details to have a better picture of what is going on)
- [ ] There is a general potential issue with scenarios like - write file -> read file if that is happening in the same location. Since we might cache listing on write and then fails with "file not found" on read. When we read a file we should just try to read it w/o hitting the listing hash.

**Comment by shcheklein** [comment]
The latest version 0.8.3 solves most of the issues in this ticket. @AlamHasabie give it a try again. Thanks for the amazing report!

**Comment by AlamHasabie** [comment]
@shcheklein issue is solved, thanks ! I'll close this ticket for now.
