### ISSUE TITLE
SignalSchemaError when saving a dataset with a list of floats.

### ISSUE THREAD

**Issue by tibor-mach** [iterative/datachain#98]
### Description

When I am running [this notebook](https://github.com/iterative/datachain/blob/llm-tutorial/examples/llm/llm_chatbot_evaluation.ipynb) (WIP for the LLM guide for datachain), I run into the following error at the first cell in the #Evaluation section when I try to save the `dc_chunks_embeddings` datachain.
```
SignalSchemaError: cannot deserialize 'document.embeddings': unknown type 'List'. Try to add it with `ModelStore.add(List)`.
```

Also, it seems that running `dc_chunks_embeddings.save()` in the previous cell is ignored as the embeddings are recalculated again (if I save it with a specific name and then load it with `.from_dataset` it works fine).

I am not sure if I am misunderstanding something or if this is indeed a bug.

### Version Info

```Text
0.2.11
Python 3.12.4
```

**Comment by dtulga** [comment]
This has been uncancelled as `List` and `Dict` support are needed for third-party model support. See this PR here which should enable this support: #422
